client_id = "66bc8d9c987f2f19758293cd78f5d469"
name = "preorder-digitalsac"
handle = "preorder-digitalsac"
application_url = "https://preorder.digitalsac.io"
embedded = true

[build]
automatically_update_urls_on_dev = false

[access_scopes]
scopes = "read_products,write_products,read_orders,write_orders,read_inventory,write_inventory,read_locations,read_publications,write_publications,read_draft_orders,write_draft_orders"

[auth]
redirect_urls = [
  "https://preorder.digitalsac.io/auth/callback",
  "https://preorder.digitalsac.io/auth/shopify/callback",
  "https://preorder.digitalsac.io/api/auth/callback"
]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["orders/paid"]
uri = "/webhooks/orders/paid"

[[webhooks.subscriptions]]
topics = ["orders/cancelled"]
uri = "/webhooks/orders/cancelled"

[[webhooks.subscriptions]]
topics = ["refunds/create"]
uri = "/webhooks/refunds/create"

[[webhooks.subscriptions]]
topics = ["products/update"]
uri = "/webhooks/products/update"
